
version: '3'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
      - "8080:8080"  # Traefik 管理界面
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  interview-backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=development
      - PORT=3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.interview.rule=PathPrefix(`/ws`)"
      - "traefik.http.routers.interview.entrypoints=web"
      - "traefik.http.services.interview.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.interview.loadbalancer.sticky.cookie.name=interview_session"
    deploy:
      replicas: 2  # 运行两个后端实例
